TRUNCATE TABLE users CASCADE;
TRUNCATE TABLE chats CASCADE;
TRUNCATE TABLE users_chats CASCADE;
TRUNCATE TABLE messages CASCADE;
TRUNCATE TABLE textinputs CASCADE;
TRUNCATE TABLE voiceinputs CASCADE;
TRUNCATE TABLE inputs CASCADE;