name: BASIC CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ yuriy_rk4 ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang-tidy cppcheck
      - run: sudo apt-get install python3-pip
      - run: pip3 install --user cpplint
      - run: sudo apt install clang-format
      - run: cppcheck internal/*/*.cpp internal/*/*.h server/*.cpp server/*.h --enable=all --inconclusive --error-exitcode=1 --std=c++20 -I internal/ server/ --suppress=missingIncludeSystem

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt install cmake gcc libgtest-dev valgrind lcov
      - run: sudo apt-get install -y clang-tools
      - run: sudo cmake .
      - run: sudo make
      - run: sudo ./alltests