name: BASIC CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ yuriy_all ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y clang-tidy cppcheck
      - run: sudo apt-get install python3-pip
      - run:  cppcheck internal/*/*.cpp internal/*/*.h main.cpp --language=c++ --enable=all --inconclusive --error-exitcode=1  -I internal/*/  --suppressions-list=list.txt

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get update -y
      - run: sudo apt install cmake g++ valgrind libboost-all-dev
      - run: sudo apt-get install -y clang-tools
      - run: sudo ./install_gtest.sh
      - run: sudo cmake .
      - run: sudo scan-build make
      - run: sudo make
      - run: sudo ./tests
      - run: sudo valgrind --tool=memcheck --leak-check=yes --error-exitcode=1 ./tests